# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 13:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, editable=False)),
                ('description', models.CharField(help_text='No máximo 50 caractéres', max_length=50, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, help_text='Por favor, use ponto em vez de vírgula', max_digits=5, verbose_name='Valor R$')),
                ('l_type', models.CharField(choices=[('en', 'Entrada'), ('ex', 'Saída')], max_length=2, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Entrie',
            fields=[
                ('launch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cashjournal.Launch')),
                ('en_type', models.CharField(choices=[('mo', 'Dinheiro'), ('ch', 'Cheque'), ('de', 'Débito'), ('cr', 'Crédito'), ('tr', 'Transferência'), ('dp', 'Depósito'), ('ot', 'Outro')], max_length=2, verbose_name='Tipo')),
            ],
            bases=('cashjournal.launch',),
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('launch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cashjournal.Launch')),
                ('ex_type', models.CharField(choices=[('pa', 'Pagamento'), ('cw', 'Retirada')], max_length=2, verbose_name='Tipo')),
            ],
            bases=('cashjournal.launch',),
        ),
        migrations.AddField(
            model_name='launch',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
