# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 11:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='No máximo 50 caractéres', max_length=50, verbose_name='Descrição')),
                ('period', models.CharField(help_text='No máximo 200 caractéres', max_length=200, verbose_name='Período de Pagamento')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor R$')),
                ('date', models.DateField(default=datetime.date.today, editable=False, verbose_name='Pago em')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
