# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 13:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controltributes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor R$')),
                ('date', models.DateField(default=datetime.date.today, editable=False, verbose_name='Pago em')),
            ],
        ),
        migrations.RemoveField(
            model_name='tribute',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tribute',
            name='value',
        ),
        migrations.AddField(
            model_name='payment',
            name='tribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controltributes.Tribute'),
        ),
    ]
